services:
  postgres:
    image: postgres:14-alpine
    container_name: tacos-db
    environment:
      POSTGRES_DB: tacos_db
      POSTGRES_USER: tacos
      POSTGRES_PASSWORD: tacos_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tacos -d tacos_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
